### ISSUE TITLE
Feature request: when using "a seperate pane for showing list" feature , can we have some way to highlight current tag？

### ISSUE THREAD

**Issue by liangzh-404** [vrtmrz/obsidian-tagfolder#75]
when using seperate pane for list in sidebar, currently I have no way to know the tag I am selecting
<img width="262" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/31941670/c553ed3e-5f8c-4c71-b9bc-7857de57d8dc">

**Comment by vrtmrz** [comment]
Thank you for asking me! And, sorry for the delayed response.

It should be shown top of the area. However, this will be scrolled out with items (This behaviour has been adjusted along File Explorer)

Probably the following CSS snippet will help us. 
```css
.nav-folder.mod-root > .tree-item-self.nav-folder-title:first-child {
	position: sticky;
    top: 0;
    background-color: var(--background-secondary);
    z-index: 10;
}
```    
If you want to limit this effect only to the separated list, please add a selector like this:
```css
[data-type="tagfolder-view-list"] .nav-folder.mod-root > .tree-item-self.nav-folder-title:first-child {
    position: sticky;
    top: 0;
    background-color: var(--background-secondary);
    z-index: 10;
}
```
